---
# tasks file for role-zabbix-server

- hosts: ec2-user
  task:

  - name: instalando o repositorio do zabiix
    yum: 
      name: rpm -Uvh https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-1.el9.noarch.rpm
      state: present
      disable_gpg_check: yes


  - name: instalando mysql e suas dependencias
    package:
        name: "{{item}}"
        state: present
        update_cache: yes
    loop: 
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - ibmysqlclient-dev
    become: true

  - name: habilitando o mysql
    service:
      name: mysql
      state: started
      enable: yes


  - name: instalando pacotes do role-zabbix-server
    yum:
      name:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-apache-conf
        - zabbix-sql-scripts
        - zabbix-selinux-policy
        - zabbix-agent
    
  - name: criando database
    mysql_db:
      name: {{ DBname }}
      collation: utf8_bin
      enconding: utf8
      login_host: localhost
      login_user: root
      login_password: root

  - name: criando user no db
    mysql_user:
      login_host: localhost
      login_user: root
      login_password: root
      name: {{ DBuser }}
      password: {{ DBpassword }}
      priv: '*.*:ALL'
      state: present
      host: localhost
    with_items:
      - "{{ zabbix_server_address }}"
      - "{{ zabbix_frontend_address }}"
      - "{{ DBHost_address }}"


  - name: unzip arquivo create.sql.gz
    command: gunzip /usr/share/zabbix-sql-scripts/mysql/server.sql.gz

  - name: importando tables para o db do zabbix
    mysql_db:
      state: import
      login_host: localhost
      login_user: root
      login_password: root
      name: {{ DBname }}
      collation: utf8_bin
      enconding: utf8
      target: /usr/share/zabbix-sql-scripts/mysql/server.sql.gz
      
  - name: copiando tamplete do zabbix server
    templates:
      - src: zabbix-server.conf
      - dest: /etc/zabbix/zabbix-server.conf

  - name: iniciando o zabbix server
    service:
      name: zabbix-server
      enable: yes
      state: restarted

  - name: iniciando o zabbix agent
    service:
      name: zabbix-agent
      enable: yes
      state: restarted

  - name: iniciando httpd
    service:
      name: httpd
      enable: yes
      state: restarted

  - name: iniciando php
    service:
      name: php-fpm
      enable: yes
      state: restarted


  ## run command ansible-playbook playbook.yml -u ec2-user --private-key id-rsa.pem -i hosts.yml